#!/usr/bin/env python3
"""Generate data/foods.json and models/food_mobilenetv2_quant.labels.txt.

Food-101 class names (alphabetical) match the usual MobileNetV2 food model export.
Run from repo root:

    python3 firmware/scripts/build_foods_db.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FOODS_PATH = ROOT / "data" / "foods.json"
LABELS_PATH = ROOT / "models" / "food_mobilenetv2_quant.labels.txt"

# Food-101 — alphabetical (standard label index order for most TFLite food models)
FOOD_101: list[str] = [
    "apple_pie",
    "baby_back_ribs",
    "baklava",
    "beef_carpaccio",
    "beef_tartare",
    "beet_salad",
    "beignets",
    "bibimbap",
    "bread_pudding",
    "breakfast_burrito",
    "bruschetta",
    "caesar_salad",
    "cannoli",
    "caprese_salad",
    "carrot_cake",
    "ceviche",
    "cheese_plate",
    "cheesecake",
    "chicken_curry",
    "chicken_quesadilla",
    "chicken_wings",
    "chocolate_cake",
    "chocolate_mousse",
    "churros",
    "clam_chowder",
    "club_sandwich",
    "crab_cakes",
    "creme_brulee",
    "croque_madame",
    "cup_cakes",
    "deviled_eggs",
    "donuts",
    "dumplings",
    "edamame",
    "eggs_benedict",
    "escargots",
    "falafel",
    "filet_mignon",
    "fish_and_chips",
    "foie_gras",
    "french_fries",
    "french_onion_soup",
    "french_toast",
    "fried_calamari",
    "fried_rice",
    "frozen_yogurt",
    "garlic_bread",
    "gnocchi",
    "greek_salad",
    "grilled_cheese_sandwich",
    "grilled_salmon",
    "guacamole",
    "gyoza",
    "hamburger",
    "hot_and_sour_soup",
    "hot_dog",
    "huevos_rancheros",
    "hummus",
    "ice_cream",
    "lasagna",
    "lobster_bisque",
    "lobster_roll_sandwich",
    "macaroni_and_cheese",
    "macarons",
    "miso_soup",
    "mussels",
    "nachos",
    "omelette",
    "onion_rings",
    "oysters",
    "pad_thai",
    "paella",
    "pancakes",
    "panna_cotta",
    "peking_duck",
    "pho",
    "pizza",
    "pork_chop",
    "poutine",
    "prime_rib",
    "pulled_pork_sandwich",
    "ramen",
    "ravioli",
    "red_velvet_cake",
    "risotto",
    "samosa",
    "sashimi",
    "scallops",
    "seaweed_salad",
    "shrimp_and_grits",
    "spaghetti_bolognese",
    "spaghetti_carbonara",
    "spring_rolls",
    "steak",
    "strawberry_shortcake",
    "sushi",
    "tacos",
    "takoyaki",
    "tiramisu",
    "tuna_tartare",
    "waffles",
]

# (risk, gerd_score, upright_hours) overrides for Food-101 ids — GERD-oriented
FOOD_101_GERD: dict[str, tuple[str, int, float]] = {
    "apple_pie": ("MEDIUM", 48, 2.25),
    "baby_back_ribs": ("HIGH", 86, 3.0),
    "baklava": ("MEDIUM", 55, 2.5),
    "beef_carpaccio": ("MEDIUM", 45, 2.0),
    "beef_tartare": ("MEDIUM", 50, 2.25),
    "beet_salad": ("LOW", 18, 1.5),
    "beignets": ("MEDIUM", 58, 2.5),
    "bibimbap": ("MEDIUM", 42, 2.25),
    "bread_pudding": ("MEDIUM", 52, 2.5),
    "breakfast_burrito": ("HIGH", 78, 3.0),
    "bruschetta": ("HIGH", 72, 3.0),
    "caesar_salad": ("MEDIUM", 48, 2.0),
    "cannoli": ("MEDIUM", 54, 2.5),
    "caprese_salad": ("MEDIUM", 40, 2.0),
    "carrot_cake": ("MEDIUM", 50, 2.25),
    "ceviche": ("MEDIUM", 38, 2.0),
    "cheese_plate": ("MEDIUM", 55, 2.5),
    "cheesecake": ("HIGH", 80, 3.0),
    "chicken_curry": ("HIGH", 88, 3.0),
    "chicken_quesadilla": ("HIGH", 76, 3.0),
    "chicken_wings": ("HIGH", 90, 3.0),
    "chocolate_cake": ("HIGH", 85, 3.0),
    "chocolate_mousse": ("HIGH", 82, 3.0),
    "churros": ("MEDIUM", 60, 2.5),
    "clam_chowder": ("MEDIUM", 45, 2.25),
    "club_sandwich": ("MEDIUM", 42, 2.0),
    "crab_cakes": ("MEDIUM", 48, 2.25),
    "creme_brulee": ("MEDIUM", 55, 2.5),
    "croque_madame": ("HIGH", 74, 3.0),
    "cup_cakes": ("MEDIUM", 52, 2.25),
    "deviled_eggs": ("MEDIUM", 46, 2.0),
    "donuts": ("HIGH", 78, 3.0),
    "dumplings": ("MEDIUM", 44, 2.25),
    "edamame": ("LOW", 12, 1.5),
    "eggs_benedict": ("HIGH", 70, 3.0),
    "escargots": ("MEDIUM", 40, 2.0),
    "falafel": ("MEDIUM", 50, 2.5),
    "filet_mignon": ("MEDIUM", 55, 2.5),
    "fish_and_chips": ("HIGH", 88, 3.0),
    "foie_gras": ("HIGH", 75, 3.0),
    "french_fries": ("HIGH", 92, 3.0),
    "french_onion_soup": ("HIGH", 68, 3.0),
    "french_toast": ("MEDIUM", 50, 2.25),
    "fried_calamari": ("HIGH", 86, 3.0),
    "fried_rice": ("MEDIUM", 58, 2.5),
    "frozen_yogurt": ("MEDIUM", 42, 2.0),
    "garlic_bread": ("HIGH", 76, 3.0),
    "gnocchi": ("MEDIUM", 46, 2.25),
    "greek_salad": ("LOW", 20, 1.5),
    "grilled_cheese_sandwich": ("MEDIUM", 62, 2.5),
    "grilled_salmon": ("LOW", 18, 2.0),
    "guacamole": ("MEDIUM", 38, 2.0),
    "gyoza": ("MEDIUM", 44, 2.25),
    "hamburger": ("HIGH", 90, 3.0),
    "hot_and_sour_soup": ("HIGH", 72, 3.0),
    "hot_dog": ("HIGH", 85, 3.0),
    "huevos_rancheros": ("HIGH", 74, 3.0),
    "hummus": ("LOW", 22, 1.5),
    "ice_cream": ("HIGH", 88, 3.0),
    "lasagna": ("HIGH", 92, 3.0),
    "lobster_bisque": ("MEDIUM", 52, 2.5),
    "lobster_roll_sandwich": ("MEDIUM", 48, 2.25),
    "macaroni_and_cheese": ("HIGH", 80, 3.0),
    "macarons": ("MEDIUM", 48, 2.25),
    "miso_soup": ("LOW", 15, 1.5),
    "mussels": ("LOW", 25, 2.0),
    "nachos": ("HIGH", 88, 3.0),
    "omelette": ("MEDIUM", 40, 2.0),
    "onion_rings": ("HIGH", 82, 3.0),
    "oysters": ("LOW", 22, 2.0),
    "pad_thai": ("HIGH", 75, 3.0),
    "paella": ("MEDIUM", 50, 2.5),
    "pancakes": ("MEDIUM", 52, 2.5),
    "panna_cotta": ("MEDIUM", 50, 2.25),
    "peking_duck": ("MEDIUM", 55, 2.5),
    "pho": ("MEDIUM", 48, 2.5),
    "pizza": ("HIGH", 95, 3.0),
    "pork_chop": ("MEDIUM", 55, 2.5),
    "poutine": ("HIGH", 88, 3.0),
    "prime_rib": ("MEDIUM", 58, 2.5),
    "pulled_pork_sandwich": ("HIGH", 78, 3.0),
    "ramen": ("MEDIUM", 55, 2.5),
    "ravioli": ("MEDIUM", 48, 2.5),
    "red_velvet_cake": ("MEDIUM", 58, 2.5),
    "risotto": ("MEDIUM", 42, 2.25),
    "samosa": ("HIGH", 72, 3.0),
    "sashimi": ("LOW", 12, 1.5),
    "scallops": ("LOW", 20, 2.0),
    "seaweed_salad": ("LOW", 10, 1.5),
    "shrimp_and_grits": ("MEDIUM", 52, 2.5),
    "spaghetti_bolognese": ("HIGH", 85, 3.0),
    "spaghetti_carbonara": ("HIGH", 82, 3.0),
    "spring_rolls": ("MEDIUM", 45, 2.25),
    "steak": ("MEDIUM", 58, 2.5),
    "strawberry_shortcake": ("MEDIUM", 50, 2.25),
    "sushi": ("LOW", 18, 2.0),
    "tacos": ("HIGH", 80, 3.0),
    "takoyaki": ("MEDIUM", 48, 2.5),
    "tiramisu": ("MEDIUM", 55, 2.5),
    "tuna_tartare": ("LOW", 20, 2.0),
    "waffles": ("MEDIUM", 50, 2.5),
}

_DEFAULT = {"LOW": (22, 1.5), "MEDIUM": (52, 2.25), "HIGH": (84, 3.0)}


def _display_name(food_id: str) -> str:
    return food_id.replace("_", " ").title()


def _entry(
    name: str,
    risk: str,
    gerd_score: int,
    upright_hours: float,
    aliases: list[str] | None = None,
) -> dict:
    body: dict = {
        "risk": risk,
        "gerd_score": gerd_score,
        "upright_hours": upright_hours,
    }
    if aliases:
        body["aliases"] = aliases
    return body


# Extra foods (not in Food-101) — common meals + GERD-specific items
EXTRA_FOODS: list[tuple[str, str, int, float, list[str]]] = [
    ("Almond milk", "LOW", 15, 1.5, ["almond_milk"]),
    ("Apple", "LOW", 12, 1.5, ["apple"]),
    ("Applesauce", "LOW", 14, 1.5, ["applesauce"]),
    ("Apricot", "LOW", 18, 1.5, []),
    ("Artichoke", "LOW", 16, 1.5, []),
    ("Asparagus", "LOW", 10, 1.5, []),
    ("Avocado", "MEDIUM", 35, 2.0, ["avocado"]),
    ("Bacon", "HIGH", 88, 3.0, ["bacon"]),
    ("Bagel", "LOW", 28, 2.0, ["bagel"]),
    ("Baked potato", "LOW", 20, 2.0, ["baked_potato"]),
    ("Banana", "LOW", 8, 1.5, ["banana"]),
    ("Barbecue", "HIGH", 86, 3.0, ["bbq", "barbecue_sauce"]),
    ("Bean soup", "MEDIUM", 38, 2.25, ["bean_soup"]),
    ("Beef stew", "MEDIUM", 50, 2.5, ["beef_stew"]),
    ("Beer", "HIGH", 90, 3.0, ["beer"]),
    ("Bell pepper", "LOW", 22, 1.5, ["bell_pepper"]),
    ("Biscuit", "LOW", 30, 2.0, []),
    ("Black beans", "LOW", 18, 2.0, ["black_beans"]),
    ("Blueberries", "LOW", 10, 1.5, ["blueberries"]),
    ("Bread", "LOW", 25, 1.5, ["bread", "white_bread", "whole_wheat_bread"]),
    ("Broccoli", "LOW", 8, 1.5, ["broccoli"]),
    ("Brown rice", "LOW", 15, 2.0, ["brown_rice"]),
    ("Brownie", "MEDIUM", 55, 2.5, ["brownie", "brownies"]),
    ("Brussels sprouts", "LOW", 12, 1.5, []),
    ("Burger", "HIGH", 92, 3.0, ["burger", "cheeseburger"]),
    ("Burrito", "HIGH", 82, 3.0, ["burrito"]),
    ("Butter", "MEDIUM", 45, 2.0, ["butter"]),
    ("Cabbage", "LOW", 10, 1.5, ["cabbage"]),
    ("Cake", "MEDIUM", 58, 2.5, ["cake"]),
    ("Candy", "MEDIUM", 52, 2.5, ["candy"]),
    ("Cantaloupe", "LOW", 8, 1.5, ["cantaloupe", "melon"]),
    ("Caramel", "MEDIUM", 50, 2.25, []),
    ("Carrot", "LOW", 8, 1.5, ["carrot", "carrots"]),
    ("Cauliflower", "LOW", 10, 1.5, ["cauliflower"]),
    ("Celery", "LOW", 8, 1.5, ["celery"]),
    ("Cereal", "LOW", 22, 1.5, ["cereal"]),
    ("Cheese", "MEDIUM", 55, 2.5, ["cheese"]),
    ("Cherry", "LOW", 20, 1.5, ["cherries"]),
    ("Chicken breast", "LOW", 18, 2.0, ["chicken_breast", "grilled_chicken"]),
    ("Chickpea", "LOW", 15, 2.0, ["chickpeas", "chickpea"]),
    ("Chili", "HIGH", 88, 3.0, ["chili", "chilli"]),
    ("Chocolate", "HIGH", 90, 3.0, ["chocolate"]),
    ("Cinnamon roll", "MEDIUM", 52, 2.5, []),
    ("Citrus", "HIGH", 92, 3.0, ["citrus", "orange", "lemon", "lime", "grapefruit"]),
    ("Coconut", "MEDIUM", 35, 2.0, ["coconut"]),
    ("Coffee", "HIGH", 88, 3.0, ["coffee", "espresso", "latte", "cappuccino"]),
    ("Cola", "HIGH", 95, 3.0, ["cola", "soda", "soft_drink"]),
    ("Cookie", "MEDIUM", 48, 2.25, ["cookie", "cookies"]),
    ("Corn", "LOW", 18, 1.5, ["corn"]),
    ("Cornbread", "LOW", 28, 2.0, []),
    ("Couscous", "LOW", 20, 2.0, []),
    ("Crackers", "LOW", 25, 1.5, ["crackers"]),
    ("Cranberry", "MEDIUM", 42, 2.0, []),
    ("Cream", "HIGH", 75, 3.0, ["cream", "heavy_cream"]),
    ("Croissant", "MEDIUM", 50, 2.5, ["croissant"]),
    ("Cucumber", "LOW", 6, 1.5, ["cucumber"]),
    ("Cupcake", "MEDIUM", 52, 2.5, ["cupcake"]),
    ("Curry", "HIGH", 85, 3.0, ["curry"]),
    ("Egg", "LOW", 15, 1.5, ["egg", "eggs", "boiled_egg"]),
    ("Eggplant", "LOW", 12, 1.5, ["eggplant"]),
    ("Enchilada", "HIGH", 82, 3.0, ["enchilada"]),
    ("Fig", "LOW", 18, 1.5, []),
    ("Fish", "LOW", 18, 2.0, ["fish", "white_fish"]),
    ("Fried chicken", "HIGH", 92, 3.0, ["fried_chicken"]),
    ("Fried egg", "MEDIUM", 42, 2.0, ["fried_egg"]),
    ("Garlic", "HIGH", 78, 3.0, ["garlic"]),
    ("Ginger", "LOW", 5, 1.5, ["ginger", "ginger_tea"]),
    ("Granola", "LOW", 25, 1.5, ["granola"]),
    ("Grape", "LOW", 15, 1.5, ["grapes", "grape"]),
    ("Grapefruit", "HIGH", 90, 3.0, ["grapefruit"]),
    ("Green beans", "LOW", 10, 1.5, ["green_beans"]),
    ("Green tea", "MEDIUM", 35, 2.0, ["green_tea"]),
    ("Ham", "MEDIUM", 52, 2.5, ["ham"]),
    ("Honey", "LOW", 28, 1.5, ["honey"]),
    ("Hot sauce", "HIGH", 95, 3.0, ["hot_sauce", "sriracha", "chili_sauce"]),
    ("Jam", "MEDIUM", 45, 2.0, ["jam", "jelly"]),
    ("Juice", "HIGH", 75, 3.0, ["juice", "orange_juice", "apple_juice"]),
    ("Kale", "LOW", 8, 1.5, ["kale"]),
    ("Kebab", "MEDIUM", 55, 2.5, ["kebab"]),
    ("Ketchup", "HIGH", 80, 3.0, ["ketchup"]),
    ("Kiwi", "MEDIUM", 38, 2.0, ["kiwi"]),
    ("Lamb", "MEDIUM", 55, 2.5, ["lamb"]),
    ("Lemon", "HIGH", 92, 3.0, ["lemon"]),
    ("Lentil", "LOW", 12, 2.0, ["lentils", "lentil_soup"]),
    ("Lettuce", "LOW", 5, 1.5, ["lettuce"]),
    ("Lime", "HIGH", 90, 3.0, ["lime"]),
    ("Macaroni", "LOW", 22, 2.0, ["macaroni"]),
    ("Mango", "LOW", 18, 1.5, ["mango"]),
    ("Mashed potato", "LOW", 22, 2.0, ["mashed_potato", "mashed_potatoes"]),
    ("Mayonnaise", "MEDIUM", 48, 2.5, ["mayonnaise", "mayo"]),
    ("Meatball", "HIGH", 78, 3.0, ["meatballs", "meatball"]),
    ("Melon", "LOW", 8, 1.5, ["melon", "honeydew"]),
    ("Milk", "MEDIUM", 45, 2.0, ["milk", "whole_milk"]),
    ("Muffin", "MEDIUM", 48, 2.25, ["muffin"]),
    ("Mushroom", "LOW", 10, 1.5, ["mushroom", "mushrooms"]),
    ("Mustard", "MEDIUM", 35, 2.0, ["mustard"]),
    ("Noodle soup", "MEDIUM", 45, 2.5, ["noodle_soup"]),
    ("Noodles", "LOW", 22, 2.0, ["noodles"]),
    ("Oatmeal", "LOW", 6, 1.5, ["oatmeal", "porridge", "oats"]),
    ("Olive", "MEDIUM", 30, 2.0, ["olives", "olive"]),
    ("Olive oil", "LOW", 20, 1.5, ["olive_oil"]),
    ("Onion", "HIGH", 75, 3.0, ["onion", "onions"]),
    ("Orange", "HIGH", 88, 3.0, ["orange"]),
    ("Papaya", "LOW", 15, 1.5, ["papaya"]),
    ("Pasta", "LOW", 25, 2.0, ["pasta", "plain_pasta"]),
    ("Peach", "LOW", 18, 1.5, ["peach"]),
    ("Peanut", "MEDIUM", 40, 2.0, ["peanuts", "peanut"]),
    ("Peanut butter", "MEDIUM", 45, 2.5, ["peanut_butter"]),
    ("Pear", "LOW", 15, 1.5, ["pear"]),
    ("Peas", "LOW", 10, 1.5, ["peas"]),
    ("Pepperoni", "HIGH", 88, 3.0, ["pepperoni"]),
    ("Pickles", "HIGH", 72, 3.0, ["pickles", "pickle"]),
    ("Pie", "MEDIUM", 52, 2.5, ["pie"]),
    ("Pineapple", "HIGH", 85, 3.0, ["pineapple"]),
    ("Plum", "LOW", 18, 1.5, ["plum"]),
    ("Popcorn", "LOW", 28, 1.5, ["popcorn"]),
    ("Pork", "MEDIUM", 55, 2.5, ["pork"]),
    ("Potato", "LOW", 20, 2.0, ["potato", "potatoes"]),
    ("Potato chips", "HIGH", 88, 3.0, ["potato_chips", "chips"]),
    ("Pretzel", "LOW", 30, 1.5, ["pretzel", "pretzels"]),
    ("Pudding", "MEDIUM", 48, 2.25, ["pudding"]),
    ("Pumpkin", "LOW", 15, 1.5, ["pumpkin"]),
    ("Quinoa", "LOW", 12, 2.0, ["quinoa"]),
    ("Radish", "LOW", 8, 1.5, []),
    ("Raspberry", "LOW", 12, 1.5, ["raspberries"]),
    ("Rice", "LOW", 12, 2.0, ["rice", "white_rice", "steamed_rice"]),
    ("Salad", "LOW", 10, 1.5, ["salad", "green_salad"]),
    ("Salami", "HIGH", 82, 3.0, ["salami"]),
    ("Salmon", "LOW", 15, 2.0, ["salmon"]),
    ("Salsa", "HIGH", 85, 3.0, ["salsa"]),
    ("Sandwich", "MEDIUM", 40, 2.0, ["sandwich"]),
    ("Sausage", "HIGH", 85, 3.0, ["sausage", "sausages"]),
    ("Scrambled eggs", "LOW", 18, 1.5, ["scrambled_eggs"]),
    ("Seafood", "LOW", 20, 2.0, ["seafood"]),
    ("Shrimp", "LOW", 18, 2.0, ["shrimp", "prawns"]),
    ("Soup", "MEDIUM", 38, 2.0, ["soup"]),
    ("Spaghetti", "MEDIUM", 55, 2.5, ["spaghetti"]),
    ("Spinach", "LOW", 6, 1.5, ["spinach"]),
    ("Strawberry", "LOW", 15, 1.5, ["strawberry", "strawberries"]),
    ("Sweet potato", "LOW", 15, 2.0, ["sweet_potato"]),
    ("Tea", "MEDIUM", 32, 2.0, ["tea", "black_tea", "herbal_tea"]),
    ("Toast", "LOW", 28, 1.5, ["toast"]),
    ("Tofu", "LOW", 10, 2.0, ["tofu"]),
    ("Tomato", "HIGH", 88, 3.0, ["tomato", "tomatoes"]),
    ("Tomato sauce", "HIGH", 92, 3.0, ["tomato_sauce", "marinara"]),
    ("Tortilla", "LOW", 25, 2.0, ["tortilla"]),
    ("Tuna", "LOW", 18, 2.0, ["tuna", "tuna_salad"]),
    ("Turkey", "LOW", 20, 2.0, ["turkey", "turkey_breast"]),
    ("Vanilla ice cream", "HIGH", 85, 3.0, ["vanilla_ice_cream"]),
    ("Vegetable soup", "LOW", 18, 2.0, ["vegetable_soup"]),
    ("Walnut", "LOW", 22, 1.5, ["walnuts", "walnut"]),
    ("Watermelon", "LOW", 6, 1.5, ["watermelon"]),
    ("Whipped cream", "HIGH", 72, 3.0, ["whipped_cream"]),
    ("Wine", "HIGH", 88, 3.0, ["wine", "red_wine", "white_wine"]),
    ("Yogurt", "LOW", 22, 1.5, ["yogurt", "greek_yogurt"]),
    ("Zucchini", "LOW", 8, 1.5, ["zucchini"]),
    # GERD-friendly staples
    ("Ginger tea", "LOW", 4, 1.5, ["ginger_tea"]),
    ("Chamomile tea", "LOW", 5, 1.5, ["chamomile_tea"]),
    ("Rice cake", "LOW", 18, 1.5, ["rice_cake"]),
    ("Turkey sandwich", "MEDIUM", 38, 2.0, ["turkey_sandwich"]),
    ("Chicken soup", "MEDIUM", 35, 2.25, ["chicken_soup"]),
    ("Peanut butter sandwich", "MEDIUM", 42, 2.25, ["peanut_butter_sandwich"]),
    ("Grilled fish", "LOW", 15, 2.0, ["grilled_fish"]),
    ("Steamed vegetables", "LOW", 5, 1.5, ["steamed_vegetables"]),
    ("Porridge", "LOW", 6, 1.5, []),
    ("Acid reflux trigger plate", "HIGH", 98, 3.5, []),
    # Fast food & common restaurant items
    ("Chicken nuggets", "HIGH", 88, 3.0, ["chicken_nuggets"]),
    ("Fish tacos", "MEDIUM", 55, 2.5, ["fish_tacos"]),
    ("Veggie burger", "MEDIUM", 42, 2.5, ["veggie_burger"]),
    ("Chicken sandwich", "MEDIUM", 48, 2.5, ["chicken_sandwich"]),
    ("Fish sandwich", "MEDIUM", 45, 2.25, ["fish_sandwich"]),
    ("Quesadilla", "HIGH", 72, 3.0, ["quesadilla"]),
    ("Nachos with cheese", "HIGH", 90, 3.0, []),
    ("Mozzarella sticks", "HIGH", 85, 3.0, ["mozzarella_sticks"]),
    ("Buffalo wings", "HIGH", 92, 3.0, ["buffalo_wings"]),
    ("Caesar wrap", "MEDIUM", 50, 2.5, []),
    ("Chicken salad", "LOW", 22, 2.0, ["chicken_salad"]),
    ("Tuna salad", "MEDIUM", 40, 2.25, []),
    ("Egg salad", "MEDIUM", 42, 2.0, []),
    ("Coleslaw", "MEDIUM", 38, 2.0, ["coleslaw"]),
    ("Mashed potatoes and gravy", "MEDIUM", 55, 2.5, []),
    ("Roast chicken", "LOW", 22, 2.5, ["roast_chicken"]),
    ("Baked chicken", "LOW", 20, 2.5, ["baked_chicken"]),
    ("Turkey breast", "LOW", 18, 2.0, []),
    ("Meatloaf", "MEDIUM", 55, 2.5, ["meatloaf"]),
    ("Spaghetti with meatballs", "HIGH", 88, 3.0, []),
    ("Tomato soup", "HIGH", 85, 3.0, ["tomato_soup"]),
    ("Cream of mushroom soup", "MEDIUM", 48, 2.25, []),
    ("Chicken noodle soup", "MEDIUM", 38, 2.25, []),
    ("Split pea soup", "LOW", 25, 2.0, []),
    ("Baked beans", "MEDIUM", 42, 2.25, ["baked_beans"]),
    ("Refried beans", "MEDIUM", 45, 2.25, []),
    ("Hummus wrap", "LOW", 22, 1.5, []),
    ("Falafel wrap", "MEDIUM", 50, 2.5, []),
    ("Shawarma", "MEDIUM", 55, 2.5, ["shawarma"]),
    ("Kebab plate", "MEDIUM", 55, 2.5, []),
    ("Gyro", "MEDIUM", 52, 2.5, ["gyro"]),
    ("Pad see ew", "MEDIUM", 55, 2.5, []),
    ("Green curry", "HIGH", 78, 3.0, ["green_curry"]),
    ("Red curry", "HIGH", 80, 3.0, ["red_curry"]),
    ("Butter chicken", "HIGH", 75, 3.0, ["butter_chicken"]),
    ("Tikka masala", "HIGH", 78, 3.0, ["tikka_masala"]),
    ("Biryani", "MEDIUM", 55, 2.5, ["biryani"]),
    ("Naan", "LOW", 28, 2.0, ["naan"]),
    ("Sushi roll", "LOW", 20, 2.0, ["sushi_roll"]),
    ("California roll", "LOW", 22, 2.0, []),
    ("Poke bowl", "LOW", 18, 2.0, ["poke_bowl"]),
    ("Teriyaki chicken", "MEDIUM", 48, 2.5, ["teriyaki_chicken"]),
    ("Stir fry vegetables", "LOW", 12, 1.5, ["stir_fry_vegetables"]),
    ("Stir fry chicken", "MEDIUM", 42, 2.25, []),
    ("Fried tofu", "MEDIUM", 40, 2.25, []),
    ("Veggie pizza", "HIGH", 82, 3.0, []),
    ("Pepperoni pizza", "HIGH", 95, 3.0, []),
    ("Margherita pizza", "HIGH", 78, 3.0, []),
    ("Cheese pizza", "HIGH", 90, 3.0, []),
    ("Breakfast cereal", "LOW", 22, 1.5, []),
    ("Protein shake", "MEDIUM", 38, 2.0, ["protein_shake"]),
    ("Smoothie", "MEDIUM", 40, 2.0, ["smoothie"]),
    ("Milkshake", "HIGH", 80, 3.0, ["milkshake"]),
    ("Iced coffee", "HIGH", 82, 3.0, ["iced_coffee"]),
    ("Energy drink", "HIGH", 92, 3.0, ["energy_drink"]),
    ("Sparkling water", "LOW", 5, 1.5, ["sparkling_water"]),
    ("Still water", "LOW", 0, 1.0, ["water"]),
    ("Herbal tea", "LOW", 8, 1.5, []),
    ("Peppermint tea", "MEDIUM", 35, 2.0, ["peppermint_tea"]),
    ("Mint", "HIGH", 70, 3.0, ["mint"]),
    ("Dark chocolate", "HIGH", 88, 3.0, ["dark_chocolate"]),
    ("Milk chocolate", "HIGH", 85, 3.0, []),
    ("White chocolate", "MEDIUM", 55, 2.5, []),
    ("Peanut butter cup", "HIGH", 80, 3.0, []),
    ("Granola bar", "MEDIUM", 42, 2.25, ["granola_bar"]),
    ("Protein bar", "MEDIUM", 40, 2.0, []),
    ("Trail mix", "MEDIUM", 38, 2.0, []),
    ("Cashews", "MEDIUM", 35, 2.0, ["cashews"]),
    ("Almonds", "LOW", 22, 1.5, []),
    ("Sunflower seeds", "LOW", 20, 1.5, []),
    ("Hummus and pita", "LOW", 25, 1.5, []),
    ("Pita bread", "LOW", 28, 1.5, ["pita", "pita_bread"]),
    ("Sourdough bread", "LOW", 30, 1.5, ["sourdough"]),
    ("Rye bread", "LOW", 28, 1.5, ["rye_bread"]),
    ("Gluten free bread", "LOW", 28, 1.5, []),
    ("Rice noodles", "LOW", 20, 2.0, []),
    ("Udon", "MEDIUM", 42, 2.25, ["udon"]),
    ("Soba", "LOW", 22, 2.0, ["soba"]),
    ("Instant noodles", "HIGH", 75, 3.0, ["instant_noodles"]),
    ("Cup noodles", "HIGH", 78, 3.0, ["cup_noodles"]),
    ("Mac and cheese", "HIGH", 80, 3.0, ["mac_and_cheese"]),
    ("Grilled vegetables", "LOW", 8, 1.5, []),
    ("Roasted vegetables", "LOW", 12, 1.5, []),
    ("Veggie omelette", "LOW", 20, 1.5, []),
    ("Cheese omelette", "MEDIUM", 48, 2.25, []),
    ("Bacon and eggs", "HIGH", 82, 3.0, []),
    ("Sausage and eggs", "HIGH", 85, 3.0, []),
    ("Pancakes with syrup", "MEDIUM", 58, 2.5, []),
    ("Waffles with syrup", "MEDIUM", 55, 2.5, []),
    ("French toast sticks", "MEDIUM", 52, 2.5, []),
    ("Hash browns", "HIGH", 78, 3.0, ["hash_browns"]),
    ("Home fries", "MEDIUM", 55, 2.5, []),
    ("Onion soup", "HIGH", 70, 3.0, []),
    ("Stuffed peppers", "MEDIUM", 45, 2.25, []),
    ("Stuffed cabbage", "MEDIUM", 42, 2.25, []),
    ("Shepherd's pie", "MEDIUM", 52, 2.5, ["shepherds_pie"]),
    ("Pot pie", "MEDIUM", 55, 2.5, ["pot_pie"]),
    ("Chicken pot pie", "MEDIUM", 55, 2.5, []),
    ("Corn dog", "HIGH", 85, 3.0, ["corn_dog"]),
    ("Fish sticks", "HIGH", 80, 3.0, ["fish_sticks"]),
    ("Chicken tenders", "HIGH", 88, 3.0, ["chicken_tenders"]),
    ("Sloppy joe", "HIGH", 75, 3.0, ["sloppy_joe"]),
    ("Philly cheesesteak", "HIGH", 85, 3.0, ["cheesesteak"]),
    ("Reuben sandwich", "HIGH", 78, 3.0, ["reuben"]),
    ("BLT sandwich", "MEDIUM", 55, 2.5, ["blt"]),
    ("Grilled cheese", "MEDIUM", 55, 2.5, []),
    ("Tuna melt", "MEDIUM", 50, 2.5, []),
    ("Cottage cheese", "MEDIUM", 38, 2.0, ["cottage_cheese"]),
    ("Cream cheese", "MEDIUM", 45, 2.25, ["cream_cheese"]),
    ("Sour cream", "MEDIUM", 48, 2.5, ["sour_cream"]),
    ("Ranch dressing", "MEDIUM", 52, 2.5, ["ranch"]),
    ("Vinaigrette", "LOW", 25, 1.5, []),
    ("Balsamic dressing", "LOW", 28, 1.5, []),
    ("Italian dressing", "MEDIUM", 45, 2.25, []),
    ("Blue cheese dressing", "MEDIUM", 55, 2.5, []),
]


def build() -> dict:
    out: dict = {}

    for fid in FOOD_101:
        risk, score, hours = FOOD_101_GERD.get(fid, ("MEDIUM", 52, 2.25))
        name = _display_name(fid)
        out[name] = _entry(name, risk, score, hours, aliases=[fid])

    for name, risk, score, hours, aliases in EXTRA_FOODS:
        if name in out:
            existing = out[name]
            existing.setdefault("aliases", [])
            for a in aliases:
                if a not in existing["aliases"]:
                    existing["aliases"].append(a)
            continue
        out[name] = _entry(name, risk, score, hours, aliases=aliases)

    return out


def main() -> None:
    foods = build()
    FOODS_PATH.parent.mkdir(parents=True, exist_ok=True)
    LABELS_PATH.parent.mkdir(parents=True, exist_ok=True)
    FOODS_PATH.write_text(json.dumps(foods, indent=2, sort_keys=True))
    LABELS_PATH.write_text("\n".join(FOOD_101) + "\n")
    low = sum(1 for v in foods.values() if v["risk"] == "LOW")
    med = sum(1 for v in foods.values() if v["risk"] == "MEDIUM")
    high = sum(1 for v in foods.values() if v["risk"] == "HIGH")
    print(f"Wrote {len(foods)} foods → {FOODS_PATH}")
    print(f"  LOW={low} MEDIUM={med} HIGH={high}")
    print(f"Wrote {len(FOOD_101)} labels → {LABELS_PATH}")


if __name__ == "__main__":
    main()
